//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.uv.leikelen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUI() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cl.uv.leikelen.Properties.GUI", typeof(GUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you accept, you would lose all not saved in actual scene.
        /// </summary>
        public static string ActualSceneWillLose {
            get {
                return ResourceManager.GetString("ActualSceneWillLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to scene.
        /// </summary>
        public static string AddToScene {
            get {
                return ResourceManager.GetString("AddToScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasn&apos;t selected a person or the person doesn&apos;t exists now.
        /// </summary>
        public static string AllPersonsNotExists {
            get {
                return ResourceManager.GetString("AllPersonsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person doesn&apos;t exists.
        /// </summary>
        public static string AllPersonsNotExistsTitle {
            get {
                return ResourceManager.GetString("AllPersonsNotExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave?.
        /// </summary>
        public static string AreSureExit {
            get {
                return ResourceManager.GetString("AreSureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associate.
        /// </summary>
        public static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atention.
        /// </summary>
        public static string Atention {
            get {
                return ResourceManager.GetString("Atention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by Erick Merino.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database engine.
        /// </summary>
        public static string BD_Engine {
            get {
                return ResourceManager.GetString("BD_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string BD_Host {
            get {
                return ResourceManager.GetString("BD_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port.
        /// </summary>
        public static string BD_Port {
            get {
                return ResourceManager.GetString("BD_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to save this data?.
        /// </summary>
        public static string confScene_SureSave {
            get {
                return ResourceManager.GetString("confScene_SureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save confirmation.
        /// </summary>
        public static string confScene_SureSaveTitle {
            get {
                return ResourceManager.GetString("confScene_SureSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright © 2017, University of Valparaíso. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current scene directory.
        /// </summary>
        public static string CurrentScene {
            get {
                return ResourceManager.GetString("CurrentScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        public static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data directory.
        /// </summary>
        public static string DataDirectory {
            get {
                return ResourceManager.GetString("DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Milliseconds threshold.
        /// </summary>
        public static string DefaultMillisecondsThreshold {
            get {
                return ResourceManager.GetString("DefaultMillisecondsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distances.
        /// </summary>
        public static string Distances {
            get {
                return ResourceManager.GetString("Distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file already exists, are you sure you want to replace it?.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File exists.
        /// </summary>
        public static string FileExistsTitle {
            get {
                return ResourceManager.GetString("FileExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graphs.
        /// </summary>
        public static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervals.
        /// </summary>
        public static string Intervals {
            get {
                return ResourceManager.GetString("Intervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modal type.
        /// </summary>
        public static string ModalType {
            get {
                return ResourceManager.GetString("ModalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only database file.
        /// </summary>
        public static string OnlyBD {
            get {
                return ResourceManager.GetString("OnlyBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bones color.
        /// </summary>
        public static string PersonBonesColor {
            get {
                return ResourceManager.GetString("PersonBonesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dots color.
        /// </summary>
        public static string PersonDotsColor {
            get {
                return ResourceManager.GetString("PersonDotsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection to the database has done successfully.
        /// </summary>
        public static string PrefBDConnectedOk {
            get {
                return ResourceManager.GetString("PrefBDConnectedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully connected.
        /// </summary>
        public static string PrefBDConnectedOkTitle {
            get {
                return ResourceManager.GetString("PrefBDConnectedOkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are some errors.
        /// </summary>
        public static string PrefBDError {
            get {
                return ResourceManager.GetString("PrefBDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are errors in the connection to the database.
        /// </summary>
        public static string PrefBDErrorConnect {
            get {
                return ResourceManager.GetString("PrefBDErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in the connection.
        /// </summary>
        public static string PrefBDErrorConnectTitle {
            get {
                return ResourceManager.GetString("PrefBDErrorConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database name is empty.
        /// </summary>
        public static string PrefBDErrorDbNameEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorDbNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine doesn&apos;t exists.
        /// </summary>
        public static string PrefBDErrorEngineDoesntExists {
            get {
                return ResourceManager.GetString("PrefBDErrorEngineDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine field is empty.
        /// </summary>
        public static string PrefBDErrorEngineEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorEngineEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host field is empty.
        /// </summary>
        public static string PrefBDErrorHostEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorHostEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is empty.
        /// </summary>
        public static string PrefBDErrorPassEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorPassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port field is empty or not valid.
        /// </summary>
        public static string PrefBDErrorPortEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorPortEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameters are the same that actually exists.
        /// </summary>
        public static string PrefBDErrorSame {
            get {
                return ResourceManager.GetString("PrefBDErrorSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters are equal.
        /// </summary>
        public static string PrefBDErrorSameTitle {
            get {
                return ResourceManager.GetString("PrefBDErrorSameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string PrefBDErrorTitle {
            get {
                return ResourceManager.GetString("PrefBDErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User field is empty.
        /// </summary>
        public static string PrefBDErrorUserEmpty {
            get {
                return ResourceManager.GetString("PrefBDErrorUserEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database will close the connection and will open a new with the entered parameters. Also, the processing and general modules will be restarted, please close all windows and instances of these modules.
        /// </summary>
        public static string PrefBDWillNew {
            get {
                return ResourceManager.GetString("PrefBDWillNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New connection.
        /// </summary>
        public static string PrefBDWillNewTitle {
            get {
                return ResourceManager.GetString("PrefBDWillNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum height of events graphs.
        /// </summary>
        public static string PrefEventsGraphMinHeight {
            get {
                return ResourceManager.GetString("PrefEventsGraphMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum height of intervals graphs.
        /// </summary>
        public static string PrefIntervalGraphMinHeight {
            get {
                return ResourceManager.GetString("PrefIntervalGraphMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record time.
        /// </summary>
        public static string RecordTime {
            get {
                return ResourceManager.GetString("RecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove last.
        /// </summary>
        public static string RemoveLast {
            get {
                return ResourceManager.GetString("RemoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When trying to save the scene has occurred the following error:.
        /// </summary>
        public static string SavedError {
            get {
                return ResourceManager.GetString("SavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save error.
        /// </summary>
        public static string SavedErrorTitle {
            get {
                return ResourceManager.GetString("SavedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scene has been saved successfully.
        /// </summary>
        public static string SavedOk {
            get {
                return ResourceManager.GetString("SavedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene saved.
        /// </summary>
        public static string SavedOkTitle {
            get {
                return ResourceManager.GetString("SavedOkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to export the scene.
        /// </summary>
        public static string SceneExportedError {
            get {
                return ResourceManager.GetString("SceneExportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export error.
        /// </summary>
        public static string SceneExportedErrorTitle {
            get {
                return ResourceManager.GetString("SceneExportedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haven&apos;t selected a file to export the scene.
        /// </summary>
        public static string SceneExportedNoFile {
            get {
                return ResourceManager.GetString("SceneExportedNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file selected.
        /// </summary>
        public static string SceneExportedNoFileTitle {
            get {
                return ResourceManager.GetString("SceneExportedNoFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scene has been exported succesfully.
        /// </summary>
        public static string SceneExportedSuccesfully {
            get {
                return ResourceManager.GetString("SceneExportedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene exported.
        /// </summary>
        public static string SceneExportedSuccesfullyTitle {
            get {
                return ResourceManager.GetString("SceneExportedSuccesfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to import the scene.
        /// </summary>
        public static string SceneImportedError {
            get {
                return ResourceManager.GetString("SceneImportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import error.
        /// </summary>
        public static string SceneImportedErrorTitle {
            get {
                return ResourceManager.GetString("SceneImportedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haven&apos;t selected a file to import the scene.
        /// </summary>
        public static string SceneImportedNoFile {
            get {
                return ResourceManager.GetString("SceneImportedNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file selected.
        /// </summary>
        public static string SceneImportedNoFileTitle {
            get {
                return ResourceManager.GetString("SceneImportedNoFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene imported.
        /// </summary>
        public static string SceneImportedSuccesfully {
            get {
                return ResourceManager.GetString("SceneImportedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scene has been imported succesfully.
        /// </summary>
        public static string SceneImportedSuccesfullyTitle {
            get {
                return ResourceManager.GetString("SceneImportedSuccesfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doesn&apos;t exists an scene in use.
        /// </summary>
        public static string SceneNotExist {
            get {
                return ResourceManager.GetString("SceneNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No scene.
        /// </summary>
        public static string SceneNotExistTitle {
            get {
                return ResourceManager.GetString("SceneNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please stop the recording first.
        /// </summary>
        public static string stopRecordFirst {
            get {
                return ResourceManager.GetString("stopRecordFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submodal type.
        /// </summary>
        public static string SubModalType {
            get {
                return ResourceManager.GetString("SubModalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to restart the app?.
        /// </summary>
        public static string SureRestartApp {
            get {
                return ResourceManager.GetString("SureRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Average duration.
        /// </summary>
        public static string TabSceneColumnAvgDuration {
            get {
                return ResourceManager.GetString("TabSceneColumnAvgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Average time.
        /// </summary>
        public static string TabSceneColumnAvgTime {
            get {
                return ResourceManager.GetString("TabSceneColumnAvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Average value.
        /// </summary>
        public static string TabSceneColumnAvgValue {
            get {
                return ResourceManager.GetString("TabSceneColumnAvgValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard deviation of duration.
        /// </summary>
        public static string TabSceneColumnStdDuration {
            get {
                return ResourceManager.GetString("TabSceneColumnStdDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard deviation of time.
        /// </summary>
        public static string TabSceneColumnStdTime {
            get {
                return ResourceManager.GetString("TabSceneColumnStdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard deviation of value.
        /// </summary>
        public static string TabSceneColumnStdValue {
            get {
                return ResourceManager.GetString("TabSceneColumnStdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total duration.
        /// </summary>
        public static string TabSceneColumnTotalDuration {
            get {
                return ResourceManager.GetString("TabSceneColumnTotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary of event submodal types.
        /// </summary>
        public static string TabSceneEventLabel {
            get {
                return ResourceManager.GetString("TabSceneEventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary of interval submodal types.
        /// </summary>
        public static string TabSceneIntervalLabel {
            get {
                return ResourceManager.GetString("TabSceneIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure scene.
        /// </summary>
        public static string Title_ConfigureScene {
            get {
                return ResourceManager.GetString("Title_ConfigureScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporal directory.
        /// </summary>
        public static string TmpDirectory {
            get {
                return ResourceManager.GetString("TmpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string ToOpen {
            get {
                return ResourceManager.GetString("ToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
