//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.uv.leikelen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cl.uv.leikelen.Properties.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string File_Export {
            get {
                return ResourceManager.GetString("File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        public static string File_Import {
            get {
                return ResourceManager.GetString("File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New scene.
        /// </summary>
        public static string File_NewScene {
            get {
                return ResourceManager.GetString("File_NewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string File_Quit {
            get {
                return ResourceManager.GetString("File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent scenes.
        /// </summary>
        public static string File_RecentScenes {
            get {
                return ResourceManager.GetString("File_RecentScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More scenes....
        /// </summary>
        public static string File_RecentScenes_More {
            get {
                return ResourceManager.GetString("File_RecentScenes_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About us.
        /// </summary>
        public static string Help_AboutUs {
            get {
                return ResourceManager.GetString("Help_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User manual.
        /// </summary>
        public static string Help_Manual {
            get {
                return ResourceManager.GetString("Help_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Person.
        /// </summary>
        public static string Scene_AddPerson {
            get {
                return ResourceManager.GetString("Scene_AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure scene.
        /// </summary>
        public static string Scene_Configure {
            get {
                return ResourceManager.GetString("Scene_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure database.
        /// </summary>
        public static string Tools_DataBase {
            get {
                return ResourceManager.GetString("Tools_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string Tools_Player {
            get {
                return ResourceManager.GetString("Tools_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View color.
        /// </summary>
        public static string Tools_Player_ColorLayerCheckbox {
            get {
                return ResourceManager.GetString("Tools_Player_ColorLayerCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View skeleton.
        /// </summary>
        public static string Tools_Player_SkeletonLayerCheckbox {
            get {
                return ResourceManager.GetString("Tools_Player_SkeletonLayerCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferences.
        /// </summary>
        public static string Tools_Preferences {
            get {
                return ResourceManager.GetString("Tools_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing Modules.
        /// </summary>
        public static string Tools_Processing {
            get {
                return ResourceManager.GetString("Tools_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add processing module (not implemented).
        /// </summary>
        public static string Tools_Processing_AddNotImplemented {
            get {
                return ResourceManager.GetString("Tools_Processing_AddNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensors.
        /// </summary>
        public static string Tools_Sensors {
            get {
                return ResourceManager.GetString("Tools_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add sensor (not implemented).
        /// </summary>
        public static string Tools_Sensors_AddNotImplemented {
            get {
                return ResourceManager.GetString("Tools_Sensors_AddNotImplemented", resourceCulture);
            }
        }
    }
}
