//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.VisualizadorMultimodal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.Kinect.VisualizadorMultimodal.Properties.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/current_scene/scene_data.db.
        /// </summary>
        internal static string CurrentDataFile {
            get {
                return ResourceManager.GetString("CurrentDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/current_scene/frames.kdvr.
        /// </summary>
        internal static string CurrentKdvrFile {
            get {
                return ResourceManager.GetString("CurrentKdvrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/current_scene.
        /// </summary>
        internal static string CurrentSceneDirectory {
            get {
                return ResourceManager.GetString("CurrentSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/imported_scene/kdvr_recorded.kdvr.
        /// </summary>
        internal static string ImportedKdvrFile {
            get {
                return ResourceManager.GetString("ImportedKdvrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/imported_scene/scene_data.db.
        /// </summary>
        internal static string ImportedSceneDataFile {
            get {
                return ResourceManager.GetString("ImportedSceneDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/imported_scene.
        /// </summary>
        internal static string ImportedSceneDirectory {
            get {
                return ResourceManager.GetString("ImportedSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/rec_scene/kdvr_recorded.kdvr.
        /// </summary>
        internal static string RecordedKdvrFilePath {
            get {
                return ResourceManager.GetString("RecordedKdvrFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/rec_scene/scene_data.db.
        /// </summary>
        internal static string RecordedSceneDataFile {
            get {
                return ResourceManager.GetString("RecordedSceneDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/rec_scene.
        /// </summary>
        internal static string RecordedSceneDirectory {
            get {
                return ResourceManager.GetString("RecordedSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/recorded_scene.mvs.
        /// </summary>
        internal static string RecordedZipFile {
            get {
                return ResourceManager.GetString("RecordedZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp.
        /// </summary>
        internal static string tmpDirectory {
            get {
                return ResourceManager.GetString("tmpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmp/rec_scene.xef.
        /// </summary>
        internal static string tmpScene {
            get {
                return ResourceManager.GetString("tmpScene", resourceCulture);
            }
        }
    }
}
