//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.uv.leikelen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cl.uv.leikelen.Properties.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/current_scene/scene_data.db.
        /// </summary>
        internal static string CurrentDataFile {
            get {
                return ResourceManager.GetString("CurrentDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/current_scene/frames.kdvr.
        /// </summary>
        internal static string CurrentKdvrFile {
            get {
                return ResourceManager.GetString("CurrentKdvrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/current_scene.
        /// </summary>
        internal static string CurrentSceneDirectory {
            get {
                return ResourceManager.GetString("CurrentSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/imported_scene/kdvr_recorded.kdvr.
        /// </summary>
        internal static string ImportedKdvrFile {
            get {
                return ResourceManager.GetString("ImportedKdvrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/imported_scene/scene_data.db.
        /// </summary>
        internal static string ImportedSceneDataFile {
            get {
                return ResourceManager.GetString("ImportedSceneDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/imported_scene.
        /// </summary>
        internal static string ImportedSceneDirectory {
            get {
                return ResourceManager.GetString("ImportedSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/rec_scene/kdvr_recorded.kdvr.
        /// </summary>
        internal static string RecordedKdvrFilePath {
            get {
                return ResourceManager.GetString("RecordedKdvrFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/rec_scene/scene_data.db.
        /// </summary>
        internal static string RecordedSceneDataFile {
            get {
                return ResourceManager.GetString("RecordedSceneDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/rec_scene.
        /// </summary>
        internal static string RecordedSceneDirectory {
            get {
                return ResourceManager.GetString("RecordedSceneDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/recorded_scene.mvs.
        /// </summary>
        internal static string RecordedZipFile {
            get {
                return ResourceManager.GetString("RecordedZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp.
        /// </summary>
        internal static string tmpDirectory {
            get {
                return ResourceManager.GetString("tmpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tmp/rec_scene.xef.
        /// </summary>
        internal static string tmpScene {
            get {
                return ResourceManager.GetString("tmpScene", resourceCulture);
            }
        }
    }
}
