//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.uv.leikelen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cl.uv.leikelen.Properties.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To CSV File.
        /// </summary>
        public static string Export_ToCSV {
            get {
                return ResourceManager.GetString("Export_ToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All events.
        /// </summary>
        public static string Export_ToCSV_Events {
            get {
                return ResourceManager.GetString("Export_ToCSV_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All intervals.
        /// </summary>
        public static string Export_ToCSV_IntervalsAll {
            get {
                return ResourceManager.GetString("Export_ToCSV_IntervalsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervals resume.
        /// </summary>
        public static string Export_ToCSV_IntervalsResume {
            get {
                return ResourceManager.GetString("Export_ToCSV_IntervalsResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To File.
        /// </summary>
        public static string Export_ToFile {
            get {
                return ResourceManager.GetString("Export_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To report in PDF.
        /// </summary>
        public static string Export_ToPDFReport {
            get {
                return ResourceManager.GetString("Export_ToPDFReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report of the person.
        /// </summary>
        public static string Export_ToPDFReport_Person {
            get {
                return ResourceManager.GetString("Export_ToPDFReport_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report of the scene.
        /// </summary>
        public static string Export_ToPDFReport_Scene {
            get {
                return ResourceManager.GetString("Export_ToPDFReport_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All scenes.
        /// </summary>
        public static string File_AllScenes {
            get {
                return ResourceManager.GetString("File_AllScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import.
        /// </summary>
        public static string File_Import {
            get {
                return ResourceManager.GetString("File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load test scene.
        /// </summary>
        public static string File_LoadTestScene {
            get {
                return ResourceManager.GetString("File_LoadTestScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New scene.
        /// </summary>
        public static string File_NewScene {
            get {
                return ResourceManager.GetString("File_NewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string File_Quit {
            get {
                return ResourceManager.GetString("File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent scenes.
        /// </summary>
        public static string File_RecentScenes {
            get {
                return ResourceManager.GetString("File_RecentScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More scenes....
        /// </summary>
        public static string File_RecentScenes_More {
            get {
                return ResourceManager.GetString("File_RecentScenes_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart app.
        /// </summary>
        public static string File_RestartApp {
            get {
                return ResourceManager.GetString("File_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About us.
        /// </summary>
        public static string Help_AboutUs {
            get {
                return ResourceManager.GetString("Help_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developer Documentation.
        /// </summary>
        public static string Help_DevDocumentation {
            get {
                return ResourceManager.GetString("Help_DevDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User manual.
        /// </summary>
        public static string Help_Manual {
            get {
                return ResourceManager.GetString("Help_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Person.
        /// </summary>
        public static string Scene_AddPerson {
            get {
                return ResourceManager.GetString("Scene_AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See all persons.
        /// </summary>
        public static string Scene_AllPersons {
            get {
                return ResourceManager.GetString("Scene_AllPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure scene.
        /// </summary>
        public static string Scene_Configure {
            get {
                return ResourceManager.GetString("Scene_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persons in scene.
        /// </summary>
        public static string Scene_PersonsInScene {
            get {
                return ResourceManager.GetString("Scene_PersonsInScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure database.
        /// </summary>
        public static string Tools_DataBase {
            get {
                return ResourceManager.GetString("Tools_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General modules.
        /// </summary>
        public static string Tools_General {
            get {
                return ResourceManager.GetString("Tools_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person sensors.
        /// </summary>
        public static string Tools_PersonSensors {
            get {
                return ResourceManager.GetString("Tools_PersonSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string Tools_Player {
            get {
                return ResourceManager.GetString("Tools_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View color.
        /// </summary>
        public static string Tools_Player_ColorLayerCheckbox {
            get {
                return ResourceManager.GetString("Tools_Player_ColorLayerCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View skeleton.
        /// </summary>
        public static string Tools_Player_SkeletonLayerCheckbox {
            get {
                return ResourceManager.GetString("Tools_Player_SkeletonLayerCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferences.
        /// </summary>
        public static string Tools_Preferences {
            get {
                return ResourceManager.GetString("Tools_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing modules.
        /// </summary>
        public static string Tools_Processing {
            get {
                return ResourceManager.GetString("Tools_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add processing module (not implemented).
        /// </summary>
        public static string Tools_Processing_AddNotImplemented {
            get {
                return ResourceManager.GetString("Tools_Processing_AddNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene sensors.
        /// </summary>
        public static string Tools_SceneSensors {
            get {
                return ResourceManager.GetString("Tools_SceneSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add sensor (not implemented).
        /// </summary>
        public static string Tools_Sensors_AddNotImplemented {
            get {
                return ResourceManager.GetString("Tools_Sensors_AddNotImplemented", resourceCulture);
            }
        }
    }
}
