//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.uv.leikelen.Module.Processing.EEGEmotion2Channels.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EEGEmotion2Channels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EEGEmotion2Channels() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cl.uv.leikelen.Module.Processing.EEGEmotion2Channels.Properties.EEGEmotion2Channe" +
                            "ls", typeof(EEGEmotion2Channels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add scenes to tag.
        /// </summary>
        public static string AddScenesToTag {
            get {
                return ResourceManager.GetString("AddScenesToTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure this data is correct?.
        /// </summary>
        public static string AreSure {
            get {
                return ResourceManager.GetString("AreSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emotion Classification with EEG.
        /// </summary>
        public static string ClassificationModuleName {
            get {
                return ResourceManager.GetString("ClassificationModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emotion detection with EEG Configuration.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete scenes from tag.
        /// </summary>
        public static string DeleteScenesFromTag {
            get {
                return ResourceManager.GetString("DeleteScenesFromTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emotion Detector with EEG.
        /// </summary>
        public static string DetectionModuleName {
            get {
                return ResourceManager.GetString("DetectionModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some fields are empty.
        /// </summary>
        public static string ErrorWindowValues {
            get {
                return ResourceManager.GetString("ErrorWindowValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorWindowValuesTitle {
            get {
                return ResourceManager.GetString("ErrorWindowValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High arousal, high valence.
        /// </summary>
        public static string HAHV {
            get {
                return ResourceManager.GetString("HAHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High arousal, low valence.
        /// </summary>
        public static string HALV {
            get {
                return ResourceManager.GetString("HALV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low arousal, high valence.
        /// </summary>
        public static string LAHV {
            get {
                return ResourceManager.GetString("LAHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low arousal, low valence.
        /// </summary>
        public static string LALV {
            get {
                return ResourceManager.GetString("LALV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a embedding dimension.
        /// </summary>
        public static string mHint {
            get {
                return ResourceManager.GetString("mHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of samples.
        /// </summary>
        public static string NHint {
            get {
                return ResourceManager.GetString("NHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a threshold value.
        /// </summary>
        public static string rHint {
            get {
                return ResourceManager.GetString("rHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sampling.
        /// </summary>
        public static string Sampling {
            get {
                return ResourceManager.GetString("Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a window size.
        /// </summary>
        public static string secsHint {
            get {
                return ResourceManager.GetString("secsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shift.
        /// </summary>
        public static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shift of samples in sample entropy.
        /// </summary>
        public static string shiftHint {
            get {
                return ResourceManager.GetString("shiftHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag to train.
        /// </summary>
        public static string TagTrain {
            get {
                return ResourceManager.GetString("TagTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File selector.
        /// </summary>
        public static string TrainerFileSelectorTitle {
            get {
                return ResourceManager.GetString("TrainerFileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scene selector.
        /// </summary>
        public static string TrainerSceneSelectorTitle {
            get {
                return ResourceManager.GetString("TrainerSceneSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use internal data.
        /// </summary>
        public static string UseInternalData {
            get {
                return ResourceManager.GetString("UseInternalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
